/* test.c generated by valac 0.42.5, the Vala compiler
 * generated from test.vala, do not modify */

/* Test libmosquitto vapi file */


#include <glib.h>
#include <glib-object.h>
#include <mosquitto.h>




void test_version (void);
void test_error (void);
void test_connack (void);
void test_option (void);
void test_log (void);
void _vala_main (void);


void
test_version (void)
{
	gint major = 0;
	gint minor = 0;
	gint revision = 0;
	gint version = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_;
	_tmp3_ = mosquitto_lib_version (&_tmp0_, &_tmp1_, &_tmp2_);
	major = _tmp0_;
	minor = _tmp1_;
	revision = _tmp2_;
	version = _tmp3_;
	g_print ("* Test version:\n");
	g_print ("libmosquito version: %d.%d.%d (%d)\n", major, minor, revision, version);
}


void
test_error (void)
{
	const gchar* _tmp0_;
	g_print ("* Test error:\n");
	_tmp0_ = mosquitto_strerror ((gint) MOSQ_ERR_CONN_PENDING);
	g_print ("Error %d: [%s]\n", (gint) MOSQ_ERR_CONN_PENDING, _tmp0_);
}


void
test_connack (void)
{
	const gchar* _tmp0_;
	g_print ("* Test connack:\n");
	_tmp0_ = mosquitto_connack_string (0);
	g_print ("Connack 0: [%s]\n", _tmp0_);
}


void
test_option (void)
{
	g_print ("* Test options enum:\n");
	g_print ("PROTOCOL_VERSION: %d\n", (gint) MOSQ_OPT_PROTOCOL_VERSION);
}


void
test_log (void)
{
	g_print ("* Test log enum:\n");
	g_print ("WARNING: 0x%x\n", (guint) MOSQ_LOG_WARNING);
	g_print ("ALL: 0x%x\n", (guint) MOSQ_LOG_ALL);
}


void
_vala_main (void)
{
	mosquitto_lib_init ();
	test_version ();
	test_error ();
	test_connack ();
	test_option ();
	test_log ();
	mosquitto_lib_cleanup ();
}


int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}



